In [2]:
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif']=['SimHei']
plt.rcParams['axes.unicode_minus'] = False

In [3]:
SupplyScore = pd.read_csv(r"F:\\24561\\Documents\\欧贝杯智能创新比赛\\数据\\SupplySort4.csv")
SupplyScore = pd.DataFrame(data=SupplyScore)
Distance = pd.read_csv(r"F:\\24561\\Documents\\欧贝杯智能创新比赛\\数据\\distance.csv")
Distance = pd.DataFrame(Distance)
Buy_City = pd.read_csv(r"F:\\24561\\Documents\\欧贝杯智能创新比赛\\数据\\Buy.csv")
Buy_City = pd.DataFrame(Buy_City)
FirstRestrain = pd.read_csv(r"F:\\24561\\Documents\\欧贝杯智能创新比赛\\数据\\trainDataRecommendID.csv")
FirstRestrain = pd.DataFrame(FirstRestrain)
FirstRestest = pd.read_csv(r"F:\\24561\\Documents\\欧贝杯智能创新比赛\\数据\\testDataRecommendID.csv")
FirstRestest = pd.DataFrame(FirstRestest)
Weighttrain = pd.read_csv(r"F:\\24561\\Documents\\欧贝杯智能创新比赛\\数据\\Weight.csv")
Weighttrain = pd.DataFrame(Weighttrain)
SupplyScore.set_index(['id（供应商代码）'], inplace=True)
Distance.set_index(['列城市'],inplace=True)
Buy_City.set_index(['id（采购商代码）'],inplace=True)
traindata = FirstRestrain
testdata = FirstRestest
testdata.reset_index(drop=True,inplace=True)
BuyIDtrain = traindata.loc[:,'id（采购商代码）']
SupplyIDtrain = traindata.loc[:,'id（供应商代码）']
RecommendIDtrain = traindata.loc[:,'Recommend']
RecommendIDtrainScore = traindata.loc[:,'Score']
BuyIDtest = testdata.loc[:,'id（采购商代码）']
SupplyIDtest = testdata.loc[:,'id（供应商代码）']
RecommendIDtest = testdata.loc[:,'Recommend']
RecommendIDtestScore = testdata.loc[:,'Score']

In [6]:
np.matrix(Weighttrain.iloc[0,:]).T

matrix([[0.9 ],
        [0.05],
        [0.05]])

In [7]:
range(Weighttrain.shape[0])

range(0, 171)

In [8]:
def Recall(BuyID,PreparedSupply,SupplySimilar,CorrectID,Weight):
    SupplyCity = SupplyScore.loc[PreparedSupply,'供应商城市'].values
    SupplyPoint = SupplyScore.loc[PreparedSupply,'综合得分指数'].values
    BuyCity = Buy_City.loc[BuyID,'采购商城市']
    Dis = 100/(Distance.loc[SupplyCity,BuyCity]+100)
    SupplySimilar = 1/(SupplySimilar+1)
    SupplyTotal = np.vstack((SupplyPoint,Dis,SupplySimilar)).T
    SupplyLastpoint = np.array(np.dot(SupplyTotal,Weight))
    sorted_id = np.argsort(-SupplyLastpoint.T)[:,:10]
    SupplyRecommend = PreparedSupply[sorted_id]
    if CorrectID in SupplyRecommend:
        return 1
    else:
        return 0

In [9]:
def JudgeHistory(CorrectID,SupplyIDtrain):
    if CorrectID in SupplyIDtrain:
        return 1
    else:
        return 0 

In [ ]:
RecallRate4 = []
for j in range(Weighttrain.shape[0]):
    Recallres = []
    for i in range(len(BuyIDtrain)):
        BuyID = BuyIDtrain[i]
        PreparedSupply = np.asarray(eval(RecommendIDtrain[i]))
        SupplySimilar = np.asarray(eval(RecommendIDtrainScore[i]))
        CorrectID = SupplyIDtrain[i]
        Weight = np.matrix(Weighttrain.iloc[j,:]).T
        Recallonce = Recall(BuyID,PreparedSupply,SupplySimilar,CorrectID,Weight)
        Recallres.append(Recallonce)
    recallrate = np.asarray(Recallres).sum()/len(Recallres)
    RecallRate4.append(recallrate)

In [34]:
BuyID = BuyIDtrain[0]
PreparedSupply = np.asarray(eval(RecommendIDtrain[0]))
SupplySimilar = np.asarray(eval(RecommendIDtrainScore[0]))
CorrectID = SupplyIDtrain[0]
Weight = np.mat('0.35;0.35;0.3')
SupplyCity = SupplyScore.loc[PreparedSupply,'供应商城市'].values
SupplyPoint = SupplyScore.loc[PreparedSupply,'综合得分指数'].values
BuyCity = Buy_City.loc[BuyID,'采购商城市']
Dis = 100/(Distance.loc[SupplyCity,BuyCity]+100)
SupplySimilar = 1/(SupplySimilar+1)
SupplyTotal = np.vstack((SupplyPoint,Dis,SupplySimilar)).T
SupplyLastpoint = np.array(np.dot(SupplyTotal,Weight))
sorted_id = np.argsort(-SupplyLastpoint.T)[:,:10]
SupplyRecommend = PreparedSupply[sorted_id]
if CorrectID in SupplyRecommend:
    print(1)
else:
    print(0)

In [ ]:
np.array(np.dot(SupplyTotal,np.matrix(Weighttrain.iloc[0,:]).T))

In [71]:
BuyID = BuyIDtrain[0]
PreparedSupply = np.asarray(eval(RecommendIDtrain[0]))
SupplySimilar = np.asarray(eval(RecommendIDtrainScore[0]))
CorrectID = SupplyIDtrain[0]
Weight = np.matrix(Weighttrain.iloc[0,:]).T
Recall(BuyID,PreparedSupply,SupplySimilar,CorrectID,Weight)

1

In [108]:
time_begin = time.time()
Recallres1 = []
for i in range(len(BuyIDtrain)):
    BuyID = BuyIDtrain[i]
    PreparedSupply = np.asarray(eval(RecommendIDtrain[i]))
    SupplySimilar = np.asarray(eval(RecommendIDtrainScore[i]))
    CorrectID = SupplyIDtrain[i]
    Weight = np.matrix(Weighttrain.iloc[170,:]).T
    Recallonce = Recall(BuyID,PreparedSupply,SupplySimilar,CorrectID,Weight)
    Recallres1.append(Recallonce)
recallrate = np.asarray(Recallres).sum()/len(Recallres)
time_end = time.time()
use_time = time_end - time_begin

In [109]:
RecallRate4.append(recallrate)

In [113]:
np.argmax(RecallRate4)

155

In [ ]:
Recallrestest = []
Intrain = []
for i in range(len(BuyIDtest)):
    BuyID = BuyIDtest[i]
    PreparedSupply = np.asarray(eval(RecommendIDtest[i]))
    SupplySimilar = np.asarray(eval(RecommendIDtestScore[i]))
    CorrectID = SupplyIDtest[i]
    Weight = np.mat('0.05;0.15;0.8')
    Recallonce = Recall(BuyID,PreparedSupply,SupplySimilar,CorrectID,Weight)
    Recallrestest.append(Recallonce)
    Judge = JudgeHistory(CorrectID,SupplyIDtrain)
    Intrain.append(Judge)
recallratetest = np.asarray(Recallrestest).sum()/len(Recallrestest)
Intrainrate = np.asarray(Intrain).sum()/len(Intrain)
recallratetest

0.19552478318097402

In [52]:
recallratetest

0.19552478318097402

In [12]:
RecallRate5 = []
for j in range(Weighttrain.shape[0]):
    Recallres = []
    for i in range(len(BuyIDtest)):
        BuyID = BuyIDtest[i]
        PreparedSupply = np.asarray(eval(RecommendIDtest[i]))
        SupplySimilar = np.asarray(eval(RecommendIDtestScore[i]))
        CorrectID = SupplyIDtest[i]
        Weight = np.matrix(Weighttrain.iloc[j,:]).T
        Recallonce = Recall(BuyID,PreparedSupply,SupplySimilar,CorrectID,Weight)
        Recallres.append(Recallonce)
    recallrate = np.asarray(Recallres).sum()/len(Recallres)
    RecallRate5.append(recallrate)

In [11]:
SupplyIDtest

0        22071
1        22071
2        22071
3        22071
4        22071
         ...  
55456     8107
55457     8107
55458     8107
55459     8107
55460     8107
Name: id（供应商代码）, Length: 55461, dtype: int64

In [17]:
RecallRate5

[0.12580011179026704,
 0.1409819512810804,
 0.1482483186383224,
 0.14898757685580857,
 0.15933719190061485,
 0.16438578460539838,
 0.1565604659129839,
 0.16764933917527633,
 0.17367158904455382,
 0.17365355835632246,
 0.1597879591063991,
 0.1732749139034637,
 0.17962171616090586,
 0.1811543246605723,
 0.17853987486702366,
 0.16195164169416346,
 0.1755467806206163,
 0.18200176700744666,
 0.18503092263031679,
 0.18555381258902653,
 0.18113629397234093,
 0.16368258776437497,
 0.17718757324967094,
 0.18348028344241898,
 0.18719460521808118,
 0.18865509096482214,
 0.18750112691801446,
 0.1831737617424857,
 0.16523322695227277,
 0.17895458069634518,
 0.18443590991868158,
 0.18856493752366527,
 0.19056634391734734,
 0.19000739258217486,
 0.18822235444726926,
 0.18420151097167378,
 0.1660446079226844,
 0.18075764951948217,
 0.18586033428895982,
 0.18881736715890446,
 0.19193667622293142,
 0.19148590901714718,
 0.19024179152918266,
 0.18952056399992787,
 0.18562593534195201,
 0.1693622545572564

In [14]:
np.argmax(RecallRate5)

127

In [16]:
RecallRate5[127]

0.1978687726510521

In [45]:
infonotinhis = pd.read_csv(r"F:\\24561\\Documents\\欧贝杯智能创新比赛\\数据\\matnotinhis.csv")

In [46]:
prepare_sup_sun = np.asarray(eval(infonotinhis.loc[0,'Recommend'])) 
similar_sup_sun = np.asarray(eval(infonotinhis.loc[0,'Score']))
prepare_sup_shimo = np.asarray(eval(infonotinhis.loc[1,'Recommend'])) 
similar_sup_shimo = np.asarray(eval(infonotinhis.loc[1,'Score']))
buyid_sun = infonotinhis.loc[0,'id（采购商代码）'] 
buyid_shimo = infonotinhis.loc[1,'id（采购商代码）'] 

In [47]:
weight = np.mat('0.15;0.4;0.45')

In [23]:
def Recall_not_in_his(BuyID,PreparedSupply,SupplySimilar,Weight):
    SupplyCity = SupplyScore.loc[PreparedSupply,'供应商城市'].values
    SupplyPoint = SupplyScore.loc[PreparedSupply,'综合得分指数'].values
    BuyCity = Buy_City.loc[BuyID,'采购商城市']
    Dis = 100/(Distance.loc[SupplyCity,BuyCity]+100)
    SupplySimilar = 1/(SupplySimilar+1)
    SupplyTotal = np.vstack((SupplyPoint,Dis,SupplySimilar)).T
    SupplyLastpoint = np.array(np.dot(SupplyTotal,Weight))
    sorted_id = np.argsort(-SupplyLastpoint.T)[:,:10]
    SupplyRecommend = PreparedSupply[sorted_id]
    return SupplyRecommend

In [ ]:
for i in range(len(BuyIDtest)):
    BuyID = BuyIDtest[i]
    PreparedSupply = np.asarray(eval(RecommendIDtest[i]))
    SupplySimilar = np.asarray(eval(RecommendIDtestScore[i]))
    CorrectID = SupplyIDtest[i]
    Weight = np.mat('0.05;0.15;0.8')
    Recallonce = Recall(BuyID,PreparedSupply,SupplySimilar,CorrectID,Weight)
    Recallrestest.append(Recallonce)
    Judge = JudgeHistory(CorrectID,SupplyIDtrain)
    Intrain.append(Judge)

In [25]:
Recall_not_in_his(buyid_sun,prepare_sup_sun,similar_sup_sun,weight)

array([[35695, 27804, 15755,  1357,  9651,  8213,    10, 19272,  6129,
         3587]])

In [48]:
Recall_not_in_his(buyid_shimo,prepare_sup_shimo,similar_sup_shimo,weight)

array([[23537, 22627,  7060,  6556, 25101, 28980, 45587,  7584, 34488,
        31685]])

In [39]:
prepare_sup_oil = np.asarray(eval(infonotinhis.loc[2,'Recommend'])) 
similar_sup_oil = np.asarray(eval(infonotinhis.loc[2,'Score']))
buyid_oil = infonotinhis.loc[2,'id（采购商代码）'] 

In [40]:
Recall_not_in_his(buyid_oil,prepare_sup_oil,similar_sup_oil,weight)

array([[26309, 43181, 28973, 35674,  4777, 20466,  9600, 30351, 38955,
        41896]])

In [43]:
print("推荐供应商")
prepare_sup_oil

推荐供应商


array([ 9600, 41896, 10681, 13094,   525,  4472, 13705, 31265, 26532,
        4472, 13705, 31265, 30634, 22022,  9600, 38955, 35674, 10448,
       28232,   525, 34176, 32462, 35766, 26532,  2949, 26309,  4777,
       43181,  5262, 30351, 20466, 29408, 44710, 21674,  6478,  7118,
       24900, 28973, 12454, 17208, 34252,  6791, 23000,  3681, 17216,
       17208])

In [44]:
print("相关供应物料相似度")
similar_sup_oil

相关供应物料相似度


array([0.99508089, 0.99508089, 0.99508089, 0.98207337, 0.97927254,
       0.97816849, 0.97816849, 0.97816849, 0.97767365, 0.97744006,
       0.97744006, 0.97744006, 0.97739756, 0.97739756, 0.97705883,
       0.97705883, 0.97705883, 0.97621334, 0.97621334, 0.97618127,
       0.97582304, 0.97582304, 0.97582304, 0.975658  , 0.9755733 ,
       0.9755733 , 0.9755733 , 0.9755733 , 0.9755733 , 0.9755733 ,
       0.9755733 , 0.97557276, 0.97557276, 0.97557276, 0.97557276,
       0.97557276, 0.97544241, 0.97544241, 0.97544241, 0.97536743,
       0.97536743, 0.97536743, 0.97532755, 0.97532755, 0.97529548,
       0.97480273])